services:
  zammad-webhook:
    image: python:3.12-slim
    container_name: zammad-webhook
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install flask requests && python alertmanager-zammad-hook.py"
    restart: unless-stopped
